import {
  NELNA_GREEN,
  NELNA_GREEN_LIGHT,
  NELNA_GREEN_DARK,
  NELNA_GOLD,
  NELNA_WHITE,
  NELNA_DARK_BG,
  NELNA_GREEN_SOFT,
  NELNA_GOLD_SOFT,
  NELNA_DARK_SOFT,
  nelnaDarkScale,
} from './src/data/brandColors.js'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        nelna: {
          green: NELNA_GREEN,
          'green-light': NELNA_GREEN_LIGHT,
          'green-dark': NELNA_GREEN_DARK,
          gold: NELNA_GOLD,
          white: NELNA_WHITE,
          dark: NELNA_DARK_BG,
          'green-soft': NELNA_GREEN_SOFT,
          'gold-soft': NELNA_GOLD_SOFT,
          'dark-soft': NELNA_DARK_SOFT,
        },
        'brand-green': {
          DEFAULT: NELNA_GREEN,
          light: NELNA_GREEN_LIGHT,
          dark: NELNA_GREEN_DARK,
          soft: NELNA_GREEN_SOFT,
          50: NELNA_GREEN_SOFT,
          100: NELNA_GREEN_SOFT,
          200: NELNA_GREEN_SOFT,
          300: NELNA_GREEN_LIGHT,
          400: NELNA_GREEN_LIGHT,
          500: NELNA_GREEN,
          600: NELNA_GREEN,
          700: NELNA_GREEN_DARK,
          800: NELNA_GREEN_DARK,
          900: NELNA_GREEN_DARK,
          950: NELNA_GREEN_DARK,
        },
        gold: {
          DEFAULT: NELNA_GOLD,
          soft: NELNA_GOLD_SOFT,
          50: NELNA_GOLD_SOFT,
          100: NELNA_GOLD_SOFT,
          200: NELNA_GOLD_SOFT,
          300: NELNA_GOLD,
          400: NELNA_GOLD,
          500: NELNA_GOLD,
          600: NELNA_GOLD,
          700: NELNA_GOLD,
          800: NELNA_GREEN_DARK,
          900: NELNA_GREEN_DARK,
        },
        'brand-yellow': {
          DEFAULT: NELNA_GOLD,
          soft: NELNA_GOLD_SOFT,
          50: NELNA_GOLD_SOFT,
          100: NELNA_GOLD_SOFT,
          200: NELNA_GOLD_SOFT,
          300: NELNA_GOLD,
          400: NELNA_GOLD,
          500: NELNA_GOLD,
          600: NELNA_GOLD,
          700: NELNA_GOLD,
          800: NELNA_GREEN_DARK,
          900: NELNA_GREEN_DARK,
        },
        brand: {
          DEFAULT: NELNA_GREEN,
          light: NELNA_GREEN_LIGHT,
          dark: NELNA_GREEN_DARK,
          soft: NELNA_GREEN_SOFT,
          50: NELNA_GREEN_SOFT,
          100: NELNA_GREEN_SOFT,
          200: NELNA_GREEN_SOFT,
          300: NELNA_GREEN_LIGHT,
          400: NELNA_GREEN_LIGHT,
          500: NELNA_GREEN,
          600: NELNA_GREEN,
          700: NELNA_GREEN_DARK,
          800: NELNA_GREEN_DARK,
          900: NELNA_GREEN_DARK,
          950: NELNA_GREEN_DARK,
        },
        primary: NELNA_GREEN,
        secondary: NELNA_GOLD,
        danger: NELNA_GREEN_DARK,
        success: NELNA_GREEN,
        warning: NELNA_GOLD,
        info: NELNA_GREEN_LIGHT,
        surface: NELNA_WHITE,
        'surface-2': NELNA_WHITE,
        'surface-3': NELNA_GREEN_SOFT,
        border: NELNA_DARK_SOFT,
        text: NELNA_DARK_BG,
        'text-2': NELNA_GREEN_DARK,
        'text-3': NELNA_DARK_BG,
        'text-inverse': NELNA_WHITE,
        ink: {
          DEFAULT: NELNA_DARK_BG,
          700: NELNA_GREEN_DARK,
          800: NELNA_GREEN_DARK,
          900: NELNA_DARK_BG,
          dark: NELNA_GREEN_DARK,
        },
        cloud: {
          DEFAULT: NELNA_WHITE,
          50: NELNA_WHITE,
          100: NELNA_GREEN_SOFT,
          soft: NELNA_GREEN_SOFT,
        },
        cream: {
          DEFAULT: NELNA_WHITE,
          warm: NELNA_GOLD_SOFT,
        },
        forest: {
          DEFAULT: NELNA_GREEN,
          mid: NELNA_GREEN_LIGHT,
          dark: NELNA_GREEN_DARK,
        },
        dark: nelnaDarkScale,
      },
      fontFamily: {
        sans: ['Manrope', 'Noto Sans Sinhala', 'Noto Sans Tamil', 'system-ui', 'sans-serif'],
        display: ['Sora', 'Manrope', 'Noto Sans Sinhala', 'Noto Sans Tamil', 'system-ui', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
      },
      spacing: {
        'section-sm': 'var(--section-spacing-sm)',
        'section-md': 'var(--section-spacing-md)',
        'section-lg': 'var(--section-spacing-lg)',
        header: 'var(--header-height)',
        topbar: 'var(--topbar-height)',
        'header-offset': 'var(--header-offset)',
      },
      maxWidth: {
        container: 'var(--container-max)',
        read: 'var(--read-max-width)',
      },
      fontSize: {
        topbar: ['var(--font-size-topbar)', { lineHeight: '1.45' }],
        nav: ['var(--font-size-nav)', { lineHeight: '1.45' }],
        body: ['var(--font-size-body)', { lineHeight: '1.65' }],
        'body-lg': ['var(--font-size-body-lg)', { lineHeight: '1.75' }],
        section: ['var(--font-size-section)', { lineHeight: '1.2' }],
        'section-lg': ['var(--font-size-section-lg)', { lineHeight: '1.15' }],
      },
      height: {
        hero: 'var(--hero-height)',
      },
      minHeight: {
        btn: 'var(--btn-height)',
      },
      zIndex: {
        dropdown: 'var(--z-dropdown)',
        header: 'var(--z-header)',
        fab: 'var(--z-fab)',
        overlay: 'var(--z-overlay)',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '24px',
        pill: '9999px',
      },
      boxShadow: {
        soft: '0 4px 20px -2px rgba(37, 27, 37, 0.08)',
        float: '0 20px 40px -4px rgba(39, 116, 58, 0.14)',
        'glow-gold': '0 0 24px rgba(216, 199, 107, 0.35)',
        card: '0 8px 24px rgba(37, 27, 37, 0.08)',
        'card-hover': '0 16px 30px rgba(37, 27, 37, 0.12)',
        popover: '0 12px 28px rgba(37, 27, 37, 0.16)',
        modal: '0 24px 40px rgba(37, 27, 37, 0.22)',
        nav: '0 8px 32px rgba(13, 48, 19, 0.08)',
      },
      transitionDuration: {
        DEFAULT: '200ms',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        kenBurns: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)' },
        },
        pageEnter: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        'ken-burns': 'kenBurns 20s ease-in-out infinite',
        'page-enter': 'pageEnter 220ms ease-out forwards',
      },
    },
  },
  plugins: [],
}
