import {
  brandGreenScale,
  nelnaGoldScale,
  NELNA_GREEN,
  NELNA_GREEN_LIGHT,
  NELNA_GREEN_DARK,
  NELNA_GOLD,
  NELNA_WHITE,
  NELNA_DARK_BG,
} from './src/data/brandColors.js'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        nelna: {
          green: NELNA_GREEN,
          'green-light': NELNA_GREEN_LIGHT,
          'green-dark': NELNA_GREEN_DARK,
          gold: NELNA_GOLD,
          white: NELNA_WHITE,
          dark: NELNA_DARK_BG,
        },
        'brand-green': brandGreenScale,
        'brand-red': {
          50: '#fdf1f1',
          100: '#fce3e3',
          200: '#f8c6c8',
          300: '#f39a9d',
          400: '#eb6166',
          500: '#da2328',
          600: '#b61c21',
          700: '#90161a',
          800: '#6f1114',
          900: '#560d10',
          950: '#320708',
        },
        'brand-yellow': nelnaGoldScale,
        gold: nelnaGoldScale,
        brand: {
          50: brandGreenScale[50],
          100: brandGreenScale[100],
          200: brandGreenScale[200],
          300: brandGreenScale[300],
          400: NELNA_GREEN_LIGHT,
          500: NELNA_GREEN,
          600: NELNA_GREEN,
          700: brandGreenScale[700],
          800: brandGreenScale[800],
          900: NELNA_GREEN_DARK,
          950: NELNA_GREEN_DARK,
        },
        accent: {
          500: '#da2328',
          600: '#b61c21',
        },
        ink: {
          900: NELNA_DARK_BG,
          800: '#1e293b',
          700: '#334155',
        },
        cloud: {
          50: NELNA_WHITE,
          100: '#f5f3ea',
        },
        cream: {
          DEFAULT: NELNA_WHITE,
          warm: '#e8e6d8',
        },
        forest: {
          DEFAULT: NELNA_GREEN,
          mid: NELNA_GREEN_LIGHT,
          dark: NELNA_GREEN_DARK,
        },
        primary: NELNA_GREEN,
        secondary: NELNA_GOLD,
        danger: '#da2328',
        success: NELNA_GREEN,
        warning: '#d97706',
        info: '#0369a1',
        surface: '#ffffff',
        'surface-2': NELNA_WHITE,
        'surface-3': '#f5f3ea',
        border: '#d6e4dc',
        text: '#0f172a',
        'text-2': '#334155',
        'text-3': '#64748b',
        'text-inverse': '#ffffff',
      },
      fontFamily: {
        sans: ['Manrope', 'Noto Sans Sinhala', 'Noto Sans Tamil', 'system-ui', 'sans-serif'],
        display: ['Sora', 'Manrope', 'Noto Sans Sinhala', 'Noto Sans Tamil', 'system-ui', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
      },
      spacing: {
        'section-sm': 'var(--section-spacing-sm)',
        'section-md': 'var(--section-spacing-md)',
        'section-lg': 'var(--section-spacing-lg)',
        header: 'var(--header-height)',
        topbar: 'var(--topbar-height)',
        'header-offset': 'var(--header-offset)',
      },
      maxWidth: {
        container: 'var(--container-max)',
      },
      height: {
        hero: 'var(--hero-height)',
      },
      minHeight: {
        btn: 'var(--btn-height)',
      },
      zIndex: {
        dropdown: 'var(--z-dropdown)',
        header: 'var(--z-header)',
        fab: 'var(--z-fab)',
        overlay: 'var(--z-overlay)',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '24px',
        pill: '9999px',
      },
      boxShadow: {
        soft: '0 4px 20px -2px rgba(37, 27, 37, 0.08)',
        float: '0 20px 40px -4px rgba(39, 116, 58, 0.14)',
        'glow-gold': '0 0 24px rgba(216, 199, 107, 0.35)',
        card: '0 8px 24px rgba(37, 27, 37, 0.08)',
        'card-hover': '0 16px 30px rgba(37, 27, 37, 0.12)',
        popover: '0 12px 28px rgba(37, 27, 37, 0.16)',
        modal: '0 24px 40px rgba(37, 27, 37, 0.22)',
        nav: '0 8px 32px rgba(13, 48, 19, 0.08)',
      },
      transitionDuration: {
        DEFAULT: '200ms',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        kenBurns: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)' },
        },
        pageEnter: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        'ken-burns': 'kenBurns 20s ease-in-out infinite',
        'page-enter': 'pageEnter 220ms ease-out forwards',
      },
    },
  },
  plugins: [],
}
